### ISSUE TITLE
Media Files

### ISSUE THREAD

**Issue by peter-evance** [mazarynio/mazaryn-python#2]
The user uploaded files like images get uploaded in the local root directory of the project, I suppose this shouldn't be the case.

**Comment by Fourteen98** [comment]
can you please clarify more in this issue, do you mean when images are uploaded by the user, it get stored in the root directory of the project.

**Comment by peter-evance** [comment]
> can you please clarify more in this issue, do you mean when images are uploaded by the user, it get stored in the root directory of the project.

I mean the code stores the user uploaded files in a root directory (static cdn) folder unto which i don't think if this should be how it's supposed to be configured. Since the user uploaded files maybe required to be uploaded somewhere else or what do you suggest?
